[package]
name = "sentiric-stt-gateway-service"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web ve Asenkron
tokio = { version = "1", features = ["full"] }
axum = "0.7"
async-stream = "0.3"
tokio-stream = "0.1"

# gRPC ve Protobuf
tonic = "0.11"
prost = "0.12"

# Yapılandırma ve Hata Yönetimi
config = "0.14"
thiserror = "1.0"
anyhow = "1.0" # main.rs'de kolay hata yönetimi için

# Loglama
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# SENTIRIC STANDARDI
[dependencies.sentiric-contracts]
git = "https://github.com/sentiric/sentiric-contracts.git"
tag = "v1.9.4"